### ISSUE TITLE
Picking Tray Clearing: Action take out and add to LU/ TU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api-legacy#812]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is only 1 action "Take out and add to HU". Using this with a selected LU on the right side moves the confirmed qty into an HU on that LU.
#### Which are the steps to reproduce?
Open try and see.
### What is the expected or desired behavior?
- Selected existing LU on the right side, selected TU on the left side: "Take out and add to LU" The TU shall be moved from left to right onto the LU without changing the TU itself. No qty entering needed.
- Selected existing TU on the right side, selected TU on the left side: "Take out and add into TU" The TU content shall be moved from left to right into the selected TU on the right side. Qty entering needes (as it is already).

**Comment by teosarca** [comment]
update, the process names are:
* Take Out TU and add to LU
* Take Out CUs and add to TU

**Comment by metas-lc** [comment]
IT
1. picked and processed some HUs to have them in picking tray clearing

2. open picking tray clearing and take out an HU
=> now you have HUs on left and right

3. select an LU from the left side
=> no matter what you select on the right side you have: "Take out and add to new HU" and "Take out HU" OK

4. select a TU from the left side and an LU on the right side: 
=> Take out TU and add to LU OK
=> i wasn't asked how many TUs i want to move. Only 1 TU is moved OK?
=> TU was moved on the right side, on the LU i selected
=> qtys updated in both places OK

5. select a TU from the left side and a TU on the right side: 
=> Take out CUs and add to TU OK
=> it asks for qty OK
=> CU was moved on the right side, on the TU i selected
=> qtys updated in both places OK

note: if you select qty CU smth like 1 (not 10 or 5 or qty that fits on TU) then you get the following error:
https://pastebin.com/Ve2aYYzD
there are some cases when it created a new ifco, but i didin't find the exact testcase

questions: shall i make a follow-up to have "take out CUs and add to TU" when you select a CU on left side as well?

**Comment by teosarca** [comment]
> => i wasn't asked how many TUs i want to move. I saw from the task that is wanted. But i had 4 aggregated TUs and only 1 moved OK?

I've implemented like that on purpose.
@metas-mk  wdyt?

**Comment by metas-lc** [comment]
See 1 and 4!

> => i wasn't asked how many TUs i want to move. I saw from the task that is wanted. But i had 4 aggregated TUs and only 1 moved OK?
1. normally we won't have this case, but it would be better to take out all TUs i selected NOK

> questions: shall i make a follow-up to have "take out CUs and add to TU" when you select a CU on left side as well?

2. there won't be cases with empty CUs OK

> note: if you select qty CU smth like 1 (not 10 or 5 or qty that fits on TU) then you get the following error:
3. could not reproduce OK

4. new: have a TU with CU on the left side. select an LU on the right side and use "Take out TU and add to LU"
=> the TU is now on both places NOK 
![image](https://user-images.githubusercontent.com/16001666/35916032-b1422666-0c11-11e8-86b3-e8d3ae19200b.png)
(even if you refresh it won't disappear)

**Comment by teosarca** [comment]
> 1. normally we won't have this case, but it would be better to take out all TUs i selected NOK

was that agreed with @metas-mk?


> 4. new: have a TU with CU on the left side. select an LU on the right side and use "Take out TU and add to LU"

cannot reproduce

**Comment by metas-mk** [comment]
@lili
> normally we won't have this case, but it would be better to take out all TUs i selected NOK

Please create a follow-up for this one.

> new: have a TU with CU on the left side. select an LU on the right side and use "Take out TU and add to LU" => the TU is now on both places NOK

Can you pls check if you can reproduce now.

**Comment by metas-lc** [comment]
> new: have a TU with CU on the left side. select an LU on the right side and use "Take out TU and add to LU"
i can still reproduce:
1. in picking terminal pick smth like 1 LU with 1 TU, then some TUs (without LUs)
2. process them
3. go to picking clearing and take out the LU
4. select the LU on right side and a TU from left side
5. run Take out TU and add to LU
=> you can see the TUs on both sides (even after you refresh/requery) NOK

>normally we won't have this case, but it would be better to take out all TUs i selected NOK
follow-up: https://github.com/metasfresh/metasfresh-webui-api/issues/897

**Comment by teosarca** [comment]
closing legacy issue
